name: Checks

env:
  go-version: "1.24"

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}

      - uses: golangci/golangci-lint-action@v6
        with:
          go-version: ${{ env.go-version }}

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}

      - name: Run tests
        run: make test
